const data = {
    products: [
      {
        _id: '1',
        name: 'Business Book of the Year 2020',
        category: 'Books',
        image: '/images/book.jpg',
        price: 120,
        countInStock: 1,
        brand: 'Big Books',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Lamp',
        category: 'Furniture',
        image: '/images/lamp.jpg',
        price: 20,
        countInStock: 0,
        brand: 'Magnolia',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Bedside Table',
        category: 'Furniture',
        image: '/images/bedsideTable.jpg',
        price: 50,
        countInStock: 10,
        brand: 'Magnolia',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Coffee Maker',
        category: 'Electronics',
        image: '/images/keurig.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Keurig',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Headphones',
        category: 'Electronics',
        image: '/images/headphones.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Beats',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Desk',
        category: 'Furniture',
        image: '/images/desk.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Magnolia',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;